---
title: "Twitter Coffee"
author: "Kyle Beall"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loading the libraries
library(tidyverse)
library(tidymodels)

# install.packages("tidytext")
library(tidytext)

# install.packages("rtweet")
library(rtweet)
```

```{r}
# loading the data
## search for 500 most recent English tweets using the chocolate hashtag
choc_tweets <- search_tweets("#chocolate", n = 500, 
                              type = "recent",
                              include_rts = FALSE, 
                             lang = "en")

## search for 1000 most recent tweets by POTUS account
potus_tweets <- search_tweets("@POTUS", 
                              n = 1000,
                              type = "recent",
                              include_rts = FALSE,
                              lang = "en")

## searching for tweets about coffee
coffee_tweets <- search_tweets("coffee",
                        n = 1800,
                        include_rts = FALSE,
                        lang = "en",
                        retryonratelimit = TRUE)
## `retryonratelimit` has to do with the twitter server and splits the query into smaller chunks

## we want to save our coffee_tweets data to a separate csv file
## using `select` to remove the "hashtags" column
coffee_tweets %>% 
  select(-hashtags, -symbols) %>%
  write_csv("coffee_tweets_7_10_21.csv")

```

```{r}
# selecting for the variables we care about 
coffee_short <- coffee_tweets %>%
  select(user_id, screen_name, created_at, text, favorite_count, retweet_count)

coffee_short %>% write_csv("coffee_short_7_10_21.csv")
```

